In [1]:
import os
import math
import numpy as np
import time

import matplotlib.pyplot as plt
%matplotlib inline
from matplotlib.colors import to_rgba
import seaborn as sns
sns.set()

from tqdm.auto import tqdm

In [2]:
import jax
import jax.numpy as jnp
print("Using jax", jax.__version__)

Using jax 0.7.0


In [3]:
a = jnp.zeros((2, 5), dtype=jnp.float32)

In [4]:
a

Array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)

In [5]:
b = jnp.arange(6)

In [6]:
b

Array([0, 1, 2, 3, 4, 5], dtype=int32)

Device array

In [7]:
b.__class__

jaxlib._jax.ArrayImpl

In [9]:
b.device

CpuDevice(id=0)

change device for array

In [10]:
jax.device_get(b)

array([0, 1, 2, 3, 4, 5], dtype=int32)

In [12]:
jax.device_put(b)

Array([0, 1, 2, 3, 4, 5], dtype=int32)

In [13]:
_.__class__

jaxlib._jax.ArrayImpl

In [14]:
print(jax.device_get.__doc__)

Transfer ``x`` to host.

If ``x`` is a pytree, then the individual buffers are copied in parallel.

Args:
  x: An array, scalar, Array or (nested) standard Python container thereof
    representing the array to be transferred to host.

Returns:
  An array or (nested) Python container thereof representing the
  value of ``x``.

Examples:
  Passing a Array:

  >>> import jax
  >>> x = jax.numpy.array([1., 2., 3.])
  >>> jax.device_get(x)
  array([1., 2., 3.], dtype=float32)

  Passing a scalar (has no effect):

  >>> jax.device_get(1)
  1

See Also:
  - device_put
  - device_put_sharded
  - device_put_replicated



In [15]:
jax.devices()

[CpuDevice(id=0)]